parameters:
  centrifugo.api.dsn: '%env(CENTRIFUGO_API_DSN)%'

services:
  %env(CENTRIFUGO_API_DSN)%: 'http://secret:secret@centrifugo:8000/api'

  # notifiers
  Atakajlo\NotificationBundle\Notification\Notifier\EmailNotifier:
    tags:
      - { name: 'notification.notifier', key: 'email' }

  Atakajlo\NotificationBundle\Notification\Notifier\WebSocketNotifier:
    tags:
      - { name: 'notification.notifier', key: 'web_socket' }

  Atakajlo\NotificationBundle\Notification\Notifier\NotifierRegistry:
    arguments:
      - !tagged { tag: 'notification.notifier', index_by: 'key' }

  Atakajlo\NotificationBundle\Notification\NotificationDescriptor:
    arguments: [[]]

  Atakajlo\NotificationBundle\Factory\Factory\ClientFactory: ~

  phpcent\Client:
    factory: ['Atakajlo\NotificationBundle\Factory\Factory\ClientFactory, 'create']
    arguments:
      - '%centrifugo.api.dsn%'